\section*{Problem 3}
\subsection*{a}
The case of our problem can be modelled as a Moran process with selection, where
\begin{itemize}
\item The population size is \( N = 1000 \).
\item There is a constant low mutation rate \( \mu = 10^{-5} \)
\item The mutant has reduced relative fitness \( r = 99/100 < 1 \) due to acquiring a deleterious mutation.
\end{itemize}
By plugging in these values to the equation of the previous exercise, we find that the fixation probability for the deleterious mutation is:
\begin{align*}
    x_1
        &= \frac{1 - 1/r}{1 - 1/r^N} \\
        &= \frac{1 - 100/99}{1 - (100/99)^{1000}} \\
        &\simeq 4.361 \cdot 10^{-7}
\end{align*}
which is pretty low.

\subsection*{b}
The probability for a mutation in a single site is \( \mu = 10^{-5} \). Let \( X \) be the number of sites mutated in a new individual. The probability that a new individual acquires at least one mutation is:
\begin{align*}
    \Pr[X \geq 1]
        &= 1 - \Pr[X < 1] \\
        &= 1 - \Pr[X = 0]
\end{align*}
where \( P[X = 0] \) is the probability of acquiring \emph{no} mutations at all. The probability that a single site does not acquire a mutation is, by definition, \( (1 - \mu) \). Mutations are supposed to occur independently at each site, therefore, the probability of no sites acquiring mutation is
\[
    P[X = 0] = (1 - \mu)^{10^6}
\]
Therefore,
\begin{align*}
    \Pr[X \geq 1] &= 1 - (1 - \mu)^{10^6}
\end{align*}
This is very close to \( 1 \), which means that it is almost certain that at least one site will acquire a mutation.

\subsection*{c}
The probability that the mutation will have fixated by time \( t \) is \( P(t) = 1 - \mathrm{e}^{-Rt} \) where \( R = N \mu \rho \). The smallest time at which the probability is at least \( 50\% \) is:
\[
    T_{1/2} = \frac{\ln 2}{R}
\]
Since this time is finite, in principle this means that the mutation will eventually fixate, if we wait long enough. The reason for this is that offspring of a healthy individual are always mutants, thus it is not possible for the all-healthy state to fixate. On the contrary, the all-mutants state is absorbing; once it occurs, it fixates. Of course, depending on the nature of the population and environment, \( T_{1/2} \) can be either a reasonable or a prohibitively long time.

\subsection*{d}
In natural populations, the stable population assumption of the Moran process does not apply. That is, populations have a dynamic size (they grow or shrink) and usually a fitness advantage does not only imply increased survivability but also increased fertility. In particular, a fitter individual not only reproduces faster but also leaves more offspring, and in general, it is not the case that for every dying individual exactly one new arises. Indeed, if the non-mutant population reproduces at a faster rate, it will restrict the mutant population's access to resources, and thus drive it away from fixation and into minority status. In practice, this means that a deleterious mutation has a very low chance of fixating; the fitter subpopulations almost always dominate.

Finally, it is worth noting that depending on other characteristics of the populations as well as the time it takes to fixate a mutation, this may never actually occur in real life, even if the fixation probability is close to \( 1 \). In viruses, for example, even if a mutation has \( \rho = 1 \), the expected time until fixation (i.\@e.\@ \(P(t)\)) can be so large that in reality the genome undergoes many more mutations and the fixation never happens.
